// const month = new Date().getMonth() + 1

export const RoadmapData = [
    {
        time: 'Q4/21',
        content: ['Found Development Team', 'Build Design Plan', 'Blockchain and NFT 2.0 research', 'Verify ideals'],
        iconList: 'list-q4-2021.svg',
        hero: 'q4-2021.png',
        place: 'place.svg',
        classHero: 'w-20vw',
        color: '#49CBD7',
        // active: false,
        // status: 'past',
    },
    {
        time: 'Q1/22',
        content: ['Development Game: The Legend Of Galaxy','Build Token economic model', 'Testnet', 'Build community', 'Marketing'],
        iconList: 'list-q1-2022.svg',
        hero: 'q1-2022.png',
        place: 'place.svg',
        classHero: 'w-50 w-10vw',
        color: '#5AABE0',
        // active: (month >= 1 && month <= 3),
        // status: (month >= 1 && month <= 3) ? 'solving' : 'past',
    },
    {
        time: 'Q2/22',
        content: ['IDO', 'INO', 'PVE 1v1 Challenge', 'Staking', 'PVE Campaign', 'Marketplace', 'Daily Quest'],
        iconList: 'list-q2-2022.svg',
        hero: 'q2-2022.png',
        place: 'place.svg',
        classHero: 'w-70 w-17vw',
        color: '#CD6CFC',
        // active: (month >= 4 && month <= 6),
        // status: month < 4 ? 'upcoming' : month > 6 ? 'past' : 'solving',
    },
    {
        time: 'Q3/22',
        content: ['Clan System', 'PVP', 'Hero Fusion', 'Skill Updates', 'Star Upgrade', 'NFT Renting'],
        iconList: 'list-q3-2022.svg',
        hero: 'q3-2022.png',
        place: 'place.svg',
        classHero: 'w-60 w-17vw',
        color: '#F45EA4',
        // active: (month >= 7 && month <= 9),
        // status: month < 7 ? 'upcoming' : month > 9 ? 'past' : 'solving',
    },
    {
        time: 'Q4/22',
        content: ['Tournament 1v1', 'Skype Tower', 'PVP Updates', 'Boss Raid', 'Even Updates', 'NFT mint'],
        iconList: 'list-q4-2022.svg',
        hero: 'q4-2022.png',
        place: 'place.svg',
        classHero: 'w-60 w-16vw',
        color: '#EF6070',
        // active: (month >= 10 && month <= 12),
        // status: month < 10 ? 'upcoming' : 'solving',
    }
]